name: CI

on:
  push:
    tags-ignore:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8,9,11,15]
    steps:
      - uses: actions/checkout@v2
      - name: install jdk
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: run tests
        run: mvn --batch-mode test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install jdk
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Sonarcloud scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar